#!/usr/bin/env bash
# This script Configure  web-01 and web-02
sudo apt-get update
apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

server_config=\
"
frontend  my_web-frontend
        bind *:80
        mode http
        default_backend my_web-backend
backend my_web-backend
        balance roundrobin
        server 180252-web-01 52.91.116.231:80 check
        server 180252-web-02 54.82.210.6:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
