#!usr/bin/env bash
# Install ufw to allow ssh, http and https and block all other traffic on web-01

apt install ufw
ufw disable
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
systemctl stop ufw
ufw allow ssh
ufw allow http
ufw allow https
systemctl start ufw
ufw --force enable
